<?php
/**
 * Transportation methods with speeds in KPH
 */
class TransportModesKPH {
    public const WALKING = 5,
        BIKING = 20,
        RUNNING = 15,
        CAR_URBAN = 50,
        CAR_HIGHWAY = 100,
        TRUCK = 70,
        MOTORCYCLE = 80,
        BUS = 60,
        TRAIN = 150,
        SUBWAY = 35,
        TRAM = 40,
        FERRY = 30,
        AIRPLANE = 900,
        HELICOPTER = 250,
        HOT_AIR_BALLOON = 15,
        SEGWAY = 20,
        SKATEBOARD_SCOOTER = 25,
        TAXI = 70,
        RENTAL_CAR = 100,
        RV = 80,
        CABLE_CAR = 20,
        ANIMAL_RIDE = 10,
        HOVERCRAFT = 70,
        SLEIGH = 20,
        JETPACK = 50,
        TROLLEY = 40,
        PARAGLIDER = 60,
        SAILBOAT = 25,
        SUBMARINE = 25,
        SPACE_SHUTTLE = 28000,
        CABLEWAY = 30,
        TUKTUK = 40,
        MONORAIL = 80,
        ELECTRIC_SCOOTER = 20,
        HOVERBOARD = 15,
        GOLF_CART = 30,
        CAMEL_RIDE = 10,
        HORSEBACK_RIDING = 12,
        RICKSHAW = 25,
        PEDICAB = 25,
        SCENIC_GONDOLA = 35,
        BICYCLE_SHARE = 20,
        SNOWBIKE = 20,
        JET_SKY = 80,
        HYDROFOIL = 70,
        SEAPLANE = 300,
        BIMPLANE = 400,
        ROCKET = 28000,
        PEDAL_BOAT = 10;
}

/**
 * Transportation methods with speeds in MPH
 */
class TransportModesMPH {
    public const WALKING = 3.1,
        BIKING = 12.4,
        RUNNING = 9.3,
        CAR_URBAN = 31,
        CAR_HIGHWAY = 62,
        TRUCK = 43.5,
        MOTORCYCLE = 50,
        BUS = 37,
        TRAIN = 93,
        SUBWAY = 22,
        TRAM = 25,
        FERRY = 18.6,
        AIRPLANE = 559,
        HELICOPTER = 155,
        HOT_AIR_BALLOON = 9.3,
        SEGWAY = 12.4,
        SKATEBOARD_SCOOTER = 15.5,
        TAXI = 43.5,
        RENTAL_CAR = 62,
        RV = 50,
        CABLE_CAR = 12.4,
        ANIMAL_RIDE = 6.2,
        HOVERCRAFT = 43.5,
        SLEIGH = 6.2,
        JETPACK = 31,
        TROLLEY = 25,
        PARAGLIDER = 37,
        SAILBOAT = 15.5,
        SUBMARINE = 15.5,
        SPACE_SHUTTLE = 1747,
        CABLEWAY = 18.6,
        TUKTUK = 24.8,
        MONORAIL = 50,
        ELECTRIC_SCOOTER = 12.4,
        HOVERBOARD = 9.3,
        GOLF_CART = 18,
        CAMEL_RIDE = 6.2,
        HORSEBACK_RIDING = 7.5,
        RICKSHAW = 15.5,
        PEDICAB = 15.5,
        SCENIC_GONDOLA = 22,
        BICYCLE_SHARE = 12.4,
        SNOWBIKE = 12.4,
        JET_SKY = 50,
        HYDROFOIL = 43.5,
        SEAPLANE = 186,
        BIMPLANE = 249,
        ROCKET = 1747,
        PEDAL_BOAT = 6.2;
}